version : '2'

services:
  db:
    image: postgres:9.5
    ports:
      - "15432:5432"
  rabbitmq:
    image: "rabbitmq:3.6.6-management"
    ports:
      - '15672:15672'
  worker:
    image: image_from_dockerfile
    working_dir: /code
    command: command_for_worker development.ini
    env_file: .env
    volumes:
      - .:/code
  web:
    image: image_from_dockerfile
    working_dir: /code
    command: pserve development.ini --reload
    ports:
      - "6543:6543"
    env_file: .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/code
